language: node_js
node_js: stable
addons:
  chrome: stable
script:
- npm test
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then npm run test:sl; fi
env:
  global:
    - secure: >-
        eOOq9v/Z0KP2JBDdpleQ644aLQ/paecq8w0PG5XGAcPYMhwk9p0sChAYpNuUzP5PWCtFziUYROFA0BPm8y5EEtJIV15H6pTVFH6fxBVW9AVK3jhpzZ8UU4MzKc9b67Mk479ts/WlAZrv7dHE53bpCKS1ToPSXyM15A79iknDD6k7iZfzZerN8ahnX4HM+5WJTeelyKklsDKiBzDZFrn39aO2IDy2OS6SSLCWiZ4qboX5LR11L4yCiFw1OrbzgeXRhlDK5lplhYU4CGnz1HIsHhYWCOzw5tmYIcXj+p7/dNeUK2y6iBas2VayFeIhouknuA+vQXwLeS+EtD50wq1TurcnF5sxZPWsYHfRoxh2h7MSPAMHEAzz35Q1Lyf08moj5JedimE6DMVghQuPO+8IyoE/4cpJU34xH5XNt8nc5b3ECLBhNvmlrWqgq34oPD8heMROc5doZiDU7HDrGuG1/KguGY1/sBgoLMVME8+PUBcLh0xOsQskrGfsvu93YTw5Nuk1IN2hUEbl/x2GNfkQeQJV/MrTl1JYzW01ETHSO1de60F68DLTfQLzjDoiUa9q5kUs4kkqeB/xuK2ZNksXBz+N7lXfVdqtpGKe51QJFGJACuliWRMlzuhAA2wKxc7MF9FB63JytlESxmd08vsOGnpB+oEqDwLTGMMDSZzFes8=
    - secure: >-
        pmHQxQX/LPG9XRSI/qJ4L9EFJEjSfCfvj3u1NfmxEH8PQvVLy9gPGp6BYDpL34VO+k2KXfV49ENwHq63R1qKjo0FB7iZbznXAEqbFNOOT2KntTKoTlEUy8TN9GGhApRi979wQC+PQnA25FkiSisVrp5Z5FtHJTdepwbAyBaWmj8UoRyOpRhvAx+C0F1ZEzwT9fqySjgGjLeN4ef3RNuInhORIabRrbnDpphRImP4uCPHZBR4QJqQ84iaOKkg4gBCZbck7swOGEbNTV5CPWsQS10NtW7vMVk/pYp6/TMHHJePUFNhOy0AG/e9+PjCMWu5CMd0IryVJm2dVQX9JGZuVD7R4Bsmn167P3TJ2E5kxEHCXtMzH4x0DjOF7PCGwCDcD8lUlXJl4JSjKBwlSQ8lOX0c2Io6wUH4lfcEdbkIY2xq4hhHcmVXlmPFRtutRhbShN+b2LOaUKZMuokq2uaGCkJGVWTzq7moNNlulhw0j25KivtHFttpxPiiRMCJoIq2QYG46C1cHi+gtWzNqxk2u6G5RXEAfBzPeVC2LXnWBDns5T+/7Z6Qa1qgMrN8EbAH69AjSZZDcXbXvGhkVhrPFSrI5uZ7ZLJMf0u3Dei9iuvx21soiYij43Xa4r50Tt1XLBevzy4gJT/+rFjnxzfjOoTMJjQaYV8Gc53ioo6XkYE=
